http { 
    limit_conn_zone $binary_remote_addr zone=addr:10m; 
    limit_rate_zone $binary_remote_addr zone=one:10m; 

    server { 
        location / { 
            limit_conn addr 1; 
            limit_rate 1k; 
        }
    }
}